title:              Development Blog
email:              shkim26blog@gmail.com
description:        Here is development blog 
author:             shkim26blog
baseurl:            ""
url:                "https://shkim26blog.github.io"

# Social Profiles
twitter_username:   
github_username:    shkim26blog
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
